[package]
name = "sys-info"
version = "0.1.0"
authors = ["tangjz <36634584@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heim = "0.0.11"